package com.seaman.constant;

public enum DocumentRenewalAction {
    CREATE, PAYMENT_SUCCESS, SEND_BACK, RESUBMIT, CHECK_DOCS, SUBMIT_TO_DEPT,
    RECORD_DEPT_RESULT, RECEIVE_FROM_DEPT, RECORD_DELIVERY,
    DELIVERY_COMPLETE, CANCEL, HARD_DELETE
}
