#spring.profiles.active=development
spring.profiles.active=prod

springdoc.api-docs.path=/smart-seaman-swagger
spring.main.allow-circular-references=true
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER

## DataSource
smart.seaman.datasource.driver=com.mysql.cj.jdbc.Driver
#smart.seaman.datasource.url=jdbc:mysql://localhost:3306/smartseaman?autoreconnect=true
#smart.seaman.datasource.username=root
#smart.seaman.datasource.password=P@ssw0rd

## DB Pro
smart.seaman.datasource.url=jdbc:mysql://dev-smartseaman-db-01-do-user-7722588-0.b.db.ondigitalocean.com:25060/seaman?autoReconnect=true&useSSL=false
smart.seaman.datasource.username=seamandb
smart.seaman.datasource.password=

## DB Dev
#smart.seaman.datasource.url=jdbc:mysql://dev-smartseaman-db-01-do-user-7722588-0.b.db.ondigitalocean.com:25060/dev-seaman?autoReconnect=true&useSSL=false
#smart.seaman.datasource.username=dev-seaman-user
#smart.seaman.datasource.password=


## Upload file to S3 ( use all PROD && DEV )d
object.store.endpoint=https://dev-smartseaman-obs-01.sgp1.digitaloceanspaces.com
object.store.key=CHANGE_ME_DO_KEY
object.store.secret=
object.store.region=Singapore
object.store.bucket=smart-seaman-bucket
object.store.path.root=documents
object.store.path.template=${object.store.path.root}/%s/certs/%s
object.store.path.documents.download=document_download
object.store.path.profiles.images=profiles/images
object.store.path.news=news
object.store.path.profile.picture=profile_picture
object.store.path.banner=banner
object.store.path.voucher=voucher
object.store.path.voucher.qr=voucher/qr

## HikariCP settings
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000

## Thymeleaf
spring.thymeleaf.check-template-location=false

## Encrypt && Decrypt key
encrypt.cert.key=CHANGE_ME_ENCRYPT_KEY
jwt.secret=

## Schedule
# cache.scheduled.notification=0 0/1 * ? * *
cache.scheduled.notification=@daily

##
# firebase.service.accoun

## Fcm
fcm.url=https://fcm.googleapis.com/fcm/send
##fcm.url=https://fcm.googleapis.com/v1/projects/smart-seaman/messages:send

#PROD
fcm.auth=

#Dev
#fcm.auth=CHANGE_ME_FCM_KEY_DEV

spring.mail.host=smtp.gmail.com
spring.mail.port=587
#spring.mail.username=sup.smartseaman
#spring.mail.password=
spring.mail.username=info.smartseaman
spring.mail.password=

#support_ssm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Prod
register.confirm.url=https://mobile.smartseaman.com/confirm-register
forgot.confirm.url=https://mobile.smartseaman.com/forgot-password

#Dev
#register.confirm.url=https://mobile-dev.smartseaman.com/confirm-register
#forgot.confirm.url=https://mobile-dev.smartseaman.com/forgot-password

### Send Email is delete user.
batch.delete.user.mobile=service.smartseaman@gmail.com
#batch.delete.user.mobile=sarunyoo.xoftspace@gmail.com

